name: wine-quality-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.10.0
      - scikit-learn==1.4.0
      - seaborn==0.13.1
      - pandas==2.1.4
      - numpy==1.26.3
      - python-dotenv==1.0.1
      - gradio>=4.44.0
      - requests==2.31.0
      - joblib==1.3.2
      - matplotlib==3.8.2
      - seaborn==0.13.1
      - openai==1.10.0
      - scipy==1.11.4